### ISSUE TITLE
First time update configuration requires a POST and not a PUT

### ISSUE THREAD

**Issue by MJonker** [IBM-Bluemix-Docs/discovery#17]
I was trying to connect WKS ML model to my WDS instance.
And the steps near the end where you create a new configuration.json file work when you have done these steps already once.
But if it is the first time, you need to POST to /configurations endpoint.

**Comment by rhorsfal** [comment]
Thank you for pointing this out. I've updated this step to discuss the possibility of creating a new configuration instead of using an existing custom configuration.

The text has been cleaned up to clarify this issue as part of the following pull request and will be reflected shortly in the built documentation:

https://github.com/IBM-Bluemix-Docs/discovery/pull/30
